<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Danh sách người dùng mẫu chuyên nghiệp cho hệ thống
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Hệ thống Admin',
                'username' => 'admin',
                'email' => 'admin@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'admin',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=admin',
                'bio' => 'Quản trị viên tối cao của hệ thống LMS.',
                'phone' => '0912345678',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Nguyễn Văn Giảng',
                'username' => 'instructor',
                'email' => 'instructor@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'instructor',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=giangvien1',
                'bio' => 'Giảng viên cấp cao với hơn 10 năm kinh nghiệm trong ngành lập trình Web Fullstack và AI.',
                'phone' => '0987654321',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Trần Đức Dũng',
                'username' => 'instructor2',
                'email' => 'instructor2@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'instructor',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=giangvien2',
                'bio' => 'Chuyên gia thiết kế giao diện UI/UX và thiết kế hệ thống sản phẩm số.',
                'phone' => '0977665544',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Võ Quốc Huy',
                'username' => 'instructor3',
                'email' => 'instructor3@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'instructor',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=giangvien3',
                'bio' => 'Kỹ sư cấu trúc dữ liệu với 8 năm kinh nghiệm tại các công ty Công nghệ hàng đầu.',
                'phone' => '0998776655',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Trần Thị Học',
                'username' => 'student',
                'email' => 'student@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'student',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=hocvien1',
                'bio' => 'Học viên đam mê lập trình web và khoa học dữ liệu.',
                'phone' => '0966554433',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Lê Văn Học',
                'username' => 'student2',
                'email' => 'student2@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'student',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=hocvien2',
                'bio' => 'Sinh viên công nghệ thông tin muốn nâng cao kỹ năng thiết kế UI/UX.',
                'phone' => '0955443322',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Phạm Minh Tuấn',
                'username' => 'student3',
                'email' => 'student3@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'student',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=hocvien3',
                'bio' => 'Lập trình viên muốn chuyển hướng sang mảng AI & Big Data.',
                'phone' => '0944332211',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Nguyễn Thị Mai',
                'username' => 'student4',
                'email' => 'student4@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'student',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=hocvien4',
                'bio' => 'Sinh viên năm thứ 3, đang tìm hiểu về lập trình ứng dụng di động.',
                'phone' => '0933221100',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Đặng Công Hùng',
                'username' => 'student5',
                'email' => 'student5@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'student',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=hocvien5',
                'bio' => 'Freelancer tự do, muốn nâng cao kỹ năng phát triển web frontend.',
                'phone' => '0922110099',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Hoàng Lan Anh',
                'username' => 'student6',
                'email' => 'student6@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'student',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=hocvien6',
                'bio' => 'Sinh viên năm nhất, bắt đầu hành trình học lập trình từ con số 0.',
                'phone' => '0911009988',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Tạ Minh Khôi',
                'username' => 'student7',
                'email' => 'student7@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'student',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=hocvien7',
                'bio' => 'Lập trình viên backend tìm hiểu thêm về DevOps và Cloud Computing.',
                'phone' => '0899887766',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Bùi Quỳnh Linh',
                'username' => 'student8',
                'email' => 'student8@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'student',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=hocvien8',
                'bio' => 'Quản lý sản phẩm tìm hiểu thêm về phát triển phần mềm để hiểu rõ hơn đội engineering.',
                'phone' => '0888776655',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Vũ Thế Anh',
                'username' => 'student9',
                'email' => 'student9@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'student',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=hocvien9',
                'bio' => 'Sinh viên chuyên ngành Toán tin, đang chuyên sâu vào Machine Learning.',
                'phone' => '0877665544',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Phan Kiều Hân',
                'username' => 'student10',
                'email' => 'student10@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'student',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=hocvien10',
                'bio' => 'Designer muốn học thêm về coding để cải thiện kỹ năng prototype interactive.',
                'phone' => '0866554433',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Trương Hoàng Phúc',
                'username' => 'student11',
                'email' => 'student11@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'role' => 'student',
                'avatar' => 'https://api.dicebear.com/7.x/adventurer/svg?seed=hocvien11',
                'bio' => 'Kỹ sư phần mềm cấp cao, tìm hiểu các công nghệ mới trong hệ sinh thái web3.',
                'phone' => '0855443322',
                'google_id' => null,
                'facebook_id' => null,
                'two_factor_enabled' => false,
                'two_factor_secret' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
