<x-student-layout title="Hồ sơ cá nhân" page-title="Hồ sơ cá nhân" breadcrumb="Cập nhật thông tin hiển thị của tài khoản học viên.">
    <div class="grid gap-5 xl:grid-cols-[18rem_minmax(0,1fr)]">
        <aside class="self-start rounded-2xl border border-slate-200 bg-white p-5 text-center shadow-sm dark:border-slate-800 dark:bg-slate-900"><img src="{{ $user->avatarUrl() }}" alt="Ảnh đại diện của {{ $user->name }}" class="mx-auto h-24 w-24 rounded-2xl object-cover ring-4 ring-blue-50 dark:ring-blue-950/40"><h2 class="mt-4 truncate text-lg font-extrabold">{{ $user->name }}</h2><p class="mt-1 break-all text-sm text-slate-500">{{ $user->email }}</p><span class="mt-3 inline-flex rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-[#0056D2] dark:bg-blue-950/40 dark:text-blue-300">Học viên</span></aside>
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6 dark:border-slate-800 dark:bg-slate-900">
            <form method="POST" action="{{ route('student.profile.update') }}" enctype="multipart/form-data" class="space-y-5" x-data="{ submitting:false }" x-on:submit="submitting=true">
                @csrf @method('PUT')
                <div class="grid gap-5 md:grid-cols-2">
                    <div><label for="name" class="mb-1.5 block text-sm font-bold">Họ và tên</label><input id="name" name="name" required maxlength="255" value="{{ old('name', $user->name) }}" class="min-h-11 w-full rounded-xl border px-3 outline-none focus:ring-2 focus:ring-blue-100 @error('name') border-rose-500 @else border-slate-300 dark:border-slate-700 @enderror dark:bg-slate-950" aria-describedby="name-error">@error('name')<p id="name-error" class="mt-1 text-xs font-semibold text-rose-600">{{ $message }}</p>@enderror</div>
                    <div><label for="username" class="mb-1.5 block text-sm font-bold">Tên đăng nhập</label><input id="username" name="username" required maxlength="32" value="{{ old('username', $user->username) }}" class="min-h-11 w-full rounded-xl border px-3 outline-none focus:ring-2 focus:ring-blue-100 @error('username') border-rose-500 @else border-slate-300 dark:border-slate-700 @enderror dark:bg-slate-950">@error('username')<p class="mt-1 text-xs font-semibold text-rose-600">{{ $message }}</p>@enderror</div>
                    <div><label for="phone" class="mb-1.5 block text-sm font-bold">Số điện thoại</label><input id="phone" name="phone" value="{{ old('phone', $user->phone) }}" class="min-h-11 w-full rounded-xl border px-3 outline-none focus:ring-2 focus:ring-blue-100 @error('phone') border-rose-500 @else border-slate-300 dark:border-slate-700 @enderror dark:bg-slate-950">@error('phone')<p class="mt-1 text-xs font-semibold text-rose-600">{{ $message }}</p>@enderror</div>
                    <div><label for="avatar" class="mb-1.5 block text-sm font-bold">Ảnh đại diện</label><input id="avatar" type="file" name="avatar" accept="image/png,image/jpeg,image/webp" class="min-h-11 w-full rounded-xl border border-slate-300 p-2 text-sm dark:border-slate-700">@error('avatar')<p class="mt-1 text-xs font-semibold text-rose-600">{{ $message }}</p>@enderror</div>
                </div>
                <div><label for="bio" class="mb-1.5 block text-sm font-bold">Giới thiệu</label><textarea id="bio" name="bio" rows="5" maxlength="1000" class="w-full rounded-xl border border-slate-300 p-3 outline-none focus:ring-2 focus:ring-blue-100 dark:border-slate-700 dark:bg-slate-950">{{ old('bio', $user->bio) }}</textarea>@error('bio')<p class="mt-1 text-xs font-semibold text-rose-600">{{ $message }}</p>@enderror</div>
                <div class="flex flex-wrap gap-3"><button type="submit" :disabled="submitting" class="min-h-11 rounded-xl bg-[#0056D2] px-5 text-sm font-bold text-white hover:bg-[#0046B8] disabled:cursor-not-allowed disabled:opacity-60"><span x-text="submitting ? 'Đang lưu...' : 'Lưu thay đổi'">Lưu thay đổi</span></button><a href="{{ route('student.profile.security') }}" class="inline-flex min-h-11 items-center rounded-xl border border-slate-200 px-5 text-sm font-bold hover:bg-slate-50 dark:border-slate-700">Đi tới bảo mật</a></div>
            </form>
        </section>
    </div>
</x-student-layout>
